# 日志配置
logging:
  level:
    org.hzero: ${LOG_LEVEL:debug}
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_order?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: root
    password: root
  redis:
      host: 172.16.211.161
      port: 6379
      database: 4
      jedis:
        pool:
          # 资源池中最大连接数
          # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
          max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
          # 资源池运行最大空闲的连接数
          # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
          max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
          # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
          # 默认 -1 表示永不超时，设置5秒
          max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}

# MyBatis Mapper 扫描
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
eureka:
  instance:
    # 以IP注册到注册中心
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    # 服务的一些元数据信息
    metadata-map:
      VERSION: 0.11.0
  client:
    serviceUrl:
      # 注册中心地址，多个用逗号隔开
      defaultZone: http://172.16.211.161:8000/eureka
      #defaultZone: http://localhost:8000/eureka
    registryFetchIntervalSeconds: 10
    disable-delta: true
hzero:
  import:
    init-table: true
  scheduler:
    auto-register: false